active_record/log_subscriber: fix SystemStackError on Rails 6
When running migrations on Rails 6 logstasher tries to log stuff but chokes on
SystemStackError:

```
SystemStackError: stack level too deep
...
/gems/activesupport-6.0.2.2/lib/active_support/core_ext/object/json.rb:172:in `map'
/gems/activesupport-6.0.2.2/lib/active_support/core_ext/object/json.rb:172:in `as_json'"
```

The problem is that Rails 6 started adding `:connection` object to the event
object, and it cannot be dumped to JSON due to the error above, and therefore
making the whole app useless.